apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-config
  labels:
    k8s-app: metricbeat
data:
  metricbeat.yml: |-
    metricbeat.config.modules:
    # Mounted `metricbeat-daemonset-modules` configmap:
      path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
      reload.enabled: false
    processors:
    - add_cloud_metadata:
    output.elasticsearch:
      hosts: ["192.168.49.2:31996"] 
      setup.dashboards.enabled: true
      setup.template.settings:
        index.number_of_shards: 5
        index.number_of_replicas: 1
        index.number_of_routing_shards: 30
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-modules
  labels:
    k8s-app: metricbeat
data:
  kubernetes.yml: |-
    - module: prometheus
      period: 10s
      hosts: ["192.168.49.2:9090"]
      metrics_path: '/federate'
      query:
        'match[]': '{__name__!=""}'
